### PR TITLE
feat(core): Support hostname validation for openssl < 1.0.2 and gnutls<3.4.6

### PR DESCRIPTION
**Pull request by the-nic**
Older versions of OpenSSL need hostname validation injected via    `SSL_CTX_set_cert_verify_callback()`. host name validation is based on boost asio implementation.

Fixes [#5019](https://sogo.nu/bugs/view.php?id=5019)

This was built  with ubuntu 12.04 (precise) and CentOS 6.

### CODE REVIEW

**Comment by the-nic** [comment]
@extrafu is this better now? It fixes openssl only, In case its still not working on older distributions (although it should be quite well supported now), my recommendation would be to disable ssl. 

I also have a fix for older gnutls versions in [another branch](https://github.com/the-nic/sope/commits/bugfix/5019-tls-hostname-v2-gnutls) but I have to test a bit more

**Comment by extrafu** [comment]
Yes and no - I am not really a fan of taking curl's code. We could re-implement the same thing in SOPE directly - it's not so many function calls. I would rather go with your original code and disable hostname validation on old distros.

**Comment by the-nic** [comment]
Thanks for the feedback.

> We could re-implement the same thing in SOPE directly - it's not so many function calls.

Note that this is security-critical code and well-tested. Reimplementations may introduce subtle changes leading to new security issues. The license itself is quite liberal.

> I would rather go with your original code and disable hostname validation on old distros.

Nonono. Please no. This shows a lack of understanding how TLS works. In this case you're actively introducing knowingly a security breach. It is just so easy to get a valid certificate for another host name. And without host name validation SOPE would simply accept it.

It is not as bad as before, when peer verification was completely disabled, since the certificate must be at least valid but the truth is, the hurdle is not much higher.

Thats why I'm saying the alternative (e.g. if you dont like the host name verification) to this PR is to disable openssl/gnutls completely. It will immediately avoid the false sense of security for the users, because the implementation is broken.

**Comment by the-nic** [comment]
I have redone the implementation for host name validation now. The code itself for openssl is much smaller now, and still works for normal and wildcard domains. It compiles on both CentOS 6, and ubuntu 14.04

**Comment by the-nic** [comment]
Same for gnutls now. Lowered the requirements to gnutls 2.12.23 (or lower).

Performed manual testing with wildcard certificates, expired certificates, untrusted certificates (openssl & gnutls)

**Comment by extrafu** [comment]
This looks good. I'll wait 2-3 days and merge it into master.

**Pull request merged**
