### PR TITLE
Revert "feat(core): Peer verification on TLS connections"

### PR DESCRIPTION
**Pull request by extrafu**
Reverts inverse-inc/sope#52

This code causes too many issues on a lot of OSes:

/usr/share/GNUstep/Makefiles/rules.make:468: recipe for target 'obj/libNGStreams.obj/NGActiveSSLSocket.m.o' failed
make[6]: *** [obj/libNGStreams.obj/NGActiveSSLSocket.m.o] Error 1
/usr/share/GNUstep/Makefiles/Instance/library.make:275: recipe for target 'internal-library-all_' failed
make[5]: *** [internal-library-all_] Error 2
/usr/share/GNUstep/Makefiles/Master/rules.make:298: recipe for target 'libNGStreams.all.library.variables' failed
make[4]: *** [libNGStreams.all.library.variables] Error 2
/usr/share/GNUstep/Makefiles/Master/library.make:37: recipe for target 'internal-all' failed
make[3]: *** [internal-all] Error 2
make[3]: Leaving directory '/root/src/sope-4.9/sope-core/NGStreams'
/usr/share/GNUstep/Makefiles/Master/serial-subdirectories.make:53: recipe for target 'internal-all' failed
make[2]: *** [internal-all] Error 2
make[2]: Leaving directory '/root/src/sope-4.9/sope-core'
/usr/share/GNUstep/Makefiles/Master/serial-subdirectories.make:53: recipe for target 'internal-all' failed
make[1]: *** [internal-all] Error 2
make[1]: Leaving directory '/root/src/sope-4.9'
debian/rules:61: recipe for target 'build-stamp' failed
make: *** [build-stamp] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed

### CODE REVIEW

**Comment by the-nic** [comment]
Whats the actual issue? Please include the compiler error messages. And the configuration, this log is not very useful.

**Comment by extrafu** [comment]
I've included them in my revert message but here they are again:

NGActiveSSLSocket.m:316:5: warning: implicit declaration of function 'SSL_get0_param' [-Wimplicit-function-declaration]
     param = SSL_get0_param(self->ssl);
     ^
NGActiveSSLSocket.m:316:11: warning: assignment makes pointer from integer without a cast
     param = SSL_get0_param(self->ssl);
           ^
NGActiveSSLSocket.m:317:5: warning: implicit declaration of function 'X509_VERIFY_PARAM_set_hostflags' [-Wimplicit-function-declaration]
     X509_VERIFY_PARAM_set_hostflags(param, X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS);
     ^
NGActiveSSLSocket.m:317:44: error: 'X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS' undeclared (first use in this function)
     X509_VERIFY_PARAM_set_hostflags(param, X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS);
                                            ^
NGActiveSSLSocket.m:317:44: note: each undeclared identifier is reported only once for each function it appears in
NGActiveSSLSocket.m:318:5: warning: implicit declaration of function 'X509_VERIFY_PARAM_set1_host' [-Wimplicit-function-declaration]
     if (!X509_VERIFY_PARAM_set1_host(param, [hostName UTF8String], 0)) {

**Comment by the-nic** [comment]
They're not in any commit message.

It looks like the openssl version is too old. What OS is this built for?

**Comment by the-nic** [comment]
I also want to emphasize that having TLS enabled without these changes is very close to snake oil. The protection given by TLS is basically disabled on so many levels if the certificate is never verified. So, it should be a quite high prioritiy to get this fixed asap

**Comment by extrafu** [comment]
It's failing on CentOS 6, Debian Squeeze, Wheezy, Jessie and all their Ubuntu counterpart.

**Comment by the-nic** [comment]
Debian Squeeze, Wheezy are end-of-life for over 2 years now. Is there still support needed? Jessie is about to go to end-of-life at the end of this month, see https://wiki.debian.org/LTS

The oldest supported ubuntu version is 14.04, see https://wiki.ubuntu.com/Releases

Would it be okay to support only active distributions?

**Comment by extrafu** [comment]
Through a CPP flag yes, which we can in the spec and control files.

**Comment by the-nic** [comment]
to be honest, i find such a policy with regard to security rather concering. i'll see what i can do

**Comment by extrafu** [comment]
I didn't say I am against merging this PR - I said we must handle old builds - we have tons of users relying on them - yes, a lot of folks are still running old distros but keep updating SOGo.

**Comment by the-nic** [comment]
I didnt mean you, i meant the clients. But i think i found a solution that also works with openssl < 1.0.2. I'll update the next days

**Pull request merged**
